/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui.PlatformEmployee;

import Ecosystem.OpenScreenSystem;
import Ecosystem.UserAccount.UserAccount;
import java.awt.CardLayout;
import javax.swing.JPanel;

/**
 *
 * @author admin
 */
public class CinemaEmployeeWorkAreaJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CinemaEmployeeWorkAreaJPanel
     */
    JPanel workArea;
    OpenScreenSystem system;
    UserAccount account;
    public CinemaEmployeeWorkAreaJPanel(JPanel workArea, UserAccount account,OpenScreenSystem system) {
        initComponents();
        this.workArea= workArea;
        this.system = system;
        this.account = account;
        setSize(750, 530);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnViewMoiveLibrary = new javax.swing.JButton();
        btnManageTimeTable = new javax.swing.JButton();
        sVGImage1 = new UIDesign.SVGImage();

        setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Blue"));

        lblTitle.setBackground(new java.awt.Color(0, 0, 153));
        lblTitle.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("Platform Employee Work Area");

        btnViewMoiveLibrary.setBackground(new java.awt.Color(0, 0, 153));
        btnViewMoiveLibrary.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnViewMoiveLibrary.setForeground(new java.awt.Color(255, 255, 255));
        btnViewMoiveLibrary.setText("View Movie Library");
        btnViewMoiveLibrary.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewMoiveLibraryActionPerformed(evt);
            }
        });

        btnManageTimeTable.setBackground(new java.awt.Color(0, 0, 153));
        btnManageTimeTable.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnManageTimeTable.setForeground(new java.awt.Color(255, 255, 255));
        btnManageTimeTable.setText("Manage Timetable");
        btnManageTimeTable.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageTimeTableActionPerformed(evt);
            }
        });

        sVGImage1.setBackground(new java.awt.Color(0, 0, 153));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(195, 195, 195)
                        .addComponent(lblTitle))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(257, 257, 257)
                        .addComponent(sVGImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(292, 292, 292)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnManageTimeTable, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnViewMoiveLibrary))))
                .addContainerGap(177, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(72, 72, 72)
                .addComponent(sVGImage1, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblTitle)
                .addGap(26, 26, 26)
                .addComponent(btnViewMoiveLibrary)
                .addGap(18, 18, 18)
                .addComponent(btnManageTimeTable)
                .addContainerGap(105, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnViewMoiveLibraryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewMoiveLibraryActionPerformed
        ViewMovieLibraryJPanel jp = new ViewMovieLibraryJPanel(workArea, account, system);
        workArea.add("ManageCustomerJPanel", jp);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnViewMoiveLibraryActionPerformed

    private void btnManageTimeTableActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageTimeTableActionPerformed
        ManageTimetableJPanel snmjp = new ManageTimetableJPanel(workArea, account, system);
        workArea.add("ManageCustomerJPanel", snmjp);
        CardLayout layout = (CardLayout)workArea.getLayout();
        layout.next(workArea);
    }//GEN-LAST:event_btnManageTimeTableActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnManageTimeTable;
    private javax.swing.JButton btnViewMoiveLibrary;
    private javax.swing.JLabel lblTitle;
    private UIDesign.SVGImage sVGImage1;
    // End of variables declaration//GEN-END:variables
}
